services:
  db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: oddly_honest
      POSTGRES_PASSWORD: password
      POSTGRES_DB: oddly_honest_development
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
